Epic: 'CS.D.EURUSD.MINI.IP'
Monitor: 'C:\inetpub\IGWebApi\Data\monitor.txt'
ApiTokenTrading: '5981476277:AAFb5dTGma3RSHStkoqwrxoP7IdKfLQ_UyU'
ChatIdTrading: '@aicodetrading'
ApiTokenMonitor: '6294115371:AAEtz_twC2-VF0NR9QtGpbKlphmBS-EE0OM'
ChatIdMonitor: '@aicodemonitor'
FattoreMoltiplicatore: '10000'
OraInizioGiornata: '8'
OraFineGiornata: '21'
GiorniChiusura: '0,6'
Calendario: ''
VolumeSoglia: '150'
SpreadSoglia: '1'
Stopmonitor: 'C:\inetpub\IGWebApi\Data\Stopmonitor.txt'
OpenPosition: 'C:\inetpub\IGWebApi\Data\openPosition.json'
CloseAllPosition: 'C:\inetpub\IGWebApi\Data\closeAllPosition.csv'
ClosePosition: 'C:\inetpub\IGWebApi\Data\closePosition.json'
Database: 'C:\inetpub\IGService\db\aicodeDatabase.db'
Strategy: 'A'
currencyCode: 'USD'
size: '1.0'
stopLevel: '10.0'
limitLevel: '10.0'
env: 'live'
userName: 'deambrosis1964'
password: 'Deambrosis1964'
apiKey: '928f2cea84968e7d2c3feee5d589218d2b95baa1'
          